### PR TITLE
Explicitly coerce TargetPublishDate into ISO8601 prior to use in json

### PR DESCRIPTION
**Pull request by riverar**
Resolves https://github.com/microsoft/StoreBroker/issues/179

### CODE REVIEW

**Comment by HowardWolosky** [comment]
Per the comments I added in #179, I'm not able to repro this problem.  Before I'd take a change to the code, I'd like to better understand why we're seeing a difference in behavior.  I'm going to close this PR down for now and we can continue the discussion via #179 until such time as we understand why you're seeing this problem and we're not.

**Comment by riverar** [comment]
@HowardWolosky If you're starting to ramp up PowerShell Core support, you may want to revisit this PR. 

Per https://github.com/microsoft/StoreBroker/issues/179#issuecomment-547650786, I suspect you're going to run into some date/time issues soon.

**Comment by HowardWolosky** [comment]
Thanks for reminding me about this, @riverar. At the time that you brought up these issues, I didn't have a good understanding of PowerShell Core and its future/direction.  I've been working with it quite a bit over in [PowerShellForGitHub](https://github.com/microsoft/PowerShellForGitHub) lately, so now I just have my head wrapped around it better.  Especially with the advent of GitHub Actions (which use PS Core), it makes a lot more sense now to make sure that this is working in all PS environments.

**Comment by riverar** [comment]
Just got the alert on this, oddly. Will get this done by EOB.

**Comment by HowardWolosky** [comment]
> Will get this done by EOB.

Thanks so much!

**Pull request merged**
